schoolproject/like/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("add/<int:id>/<int:usere>/",views.like_add, name="like")
]

schoolproject/posts/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name = 'index'),
    path('post/<str:id>/', post, name = 'post'),
    path('newpost/', newpost, name='newpost'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolproject/schoolproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('like/',include("like.urls")),
    path('',include('posts.urls')),
    path('user/', include('users.urls')),
    path("auth/", include("user.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolproject/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("signup/", views.sign, name="signup"),
]

schoolproject/users/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('<str:id>/', profile, name = 'profile')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolproject/like/models.py
from django.db import models
from posts.models import Post
from django.conf import settings

class Like(models.Model):
    post = models.ForeignKey(Post,on_delete=models.SET_NULL,null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True)
    like = models.BooleanField(default=False)

schoolproject/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

user = get_user_model()

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length = 100)
    text = models.TextField()
    author = models.ForeignKey(user, on_delete = models.CASCADE)
    img = models.ImageField()
    pub_date = models.DateField(auto_now=True)
    is_liked_by_current_user = models.BooleanField(default=False)
    likes = models.IntegerField(default=0)

    
    def __str__(self):
        return self.title 

schoolproject/user/models.py
from django.db import models

# Create your models here.

schoolproject/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image

class ExtendedUser(AbstractUser):
    image = models.ImageField(upload_to="media", blank = False, null = False)
    desc = models.TextField(default="Hello. Nice to meet u!", max_length=30)

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        img = img.resize((300,300))
        img.save(self.image.path)
    

schoolproject/posts/forms.py
from .models import Post
from django.forms import ModelForm


class NewPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title','text','img')

schoolproject/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()

class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email", "image", "desc")

        

schoolproject/like/views.py
from django.shortcuts import render, redirect
from posts.models import Post
from .models import Like
from users.models import ExtendedUser

def like_add(request,id,usere):
    posto=Post.objects.get(id = id)
    usero=ExtendedUser.objects.get(id=usere)
    try:
       lik = Like.objects.get(post=posto,user=usero)
       lik.delete()
    except Exception as e:
       like = Like(post=Post.objects.get(id = id),user=ExtendedUser.objects.get(id=usere),like=True)
       like.save()
    referer = request.META.get('HTTP_REFERER')
    return redirect(referer)

schoolproject/posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post
from like.models import Like
from .forms import NewPostForm

def index(request):
    likes = Like.objects.all()
    posts = Post.objects.all()
    for post in posts:
        post.likes = Like.objects.filter(post=post).all().__len__()
        try:
                like = Like.objects.get(post=post,user=request.user)
        except Exception as e:
                like = None
        if like in likes:
                post.is_liked_by_current_user = True
        else:
                post.is_liked_by_current_user = False
    return render(request, 'index.html', {'posts': posts})

def post(request,id):
    likes = Like.objects.all()
    post = Post.objects.get(id = id)
    post.likes = Like.objects.filter(post=post).all().__len__()
    try:
        like = Like.objects.get(post=post,user=request.user)
    except Exception as e:
        like = None
    if like in likes:
        post.is_liked_by_current_user = True
    else:
        post.is_liked_by_current_user = False
    return render(request,'post.html',{'post':post})

def newpost(request):
    if request.method == 'POST':
        form = NewPostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('index')
        return render(request, "newpost.html",{"form": form})
    form = NewPostForm()
    return render(request, "newpost.html",{"form": form})

schoolproject/user/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("login")
    template_name = "signup.html"

def sign(request):
    form = CreationForm
    if request.method == "POST":
        form = CreationForm(request.POST,request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect(reverse_lazy("login"))
        else:
          print(request.POST)
          form = CreationForm()

    return render(request, 'signup.html', locals())

schoolproject/users/views.py
from django.shortcuts import render
from .models import ExtendedUser
from posts.models import Post
from like.models import Like

def profile(request,id):
    likes = Like.objects.all()
    person = ExtendedUser.objects.get(id = id)
    posts = Post.objects.filter(author = person).all()
    for post in posts:
        post.likes = Like.objects.filter(post=post).all().__len__()
        try:
                like = Like.objects.get(post=post,user=request.user)
        except Exception as e:
                like = None
        if like in likes:
                post.is_liked_by_current_user = True
        else:
                post.is_liked_by_current_user = False
    return render(request,'profile.html',{ 'user' : person, "posts" : posts })

schoolproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.15.4-web/css/all.min.css' %}">
    <script defer src="{% static 'fontawesome-free-5.15.4-web/js/all.js' %}"></script>
    <link rel="stylesheet" href="{% static 'normalize.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'logo.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Shippori+Antique&display=swap" rel="stylesheet">
    <title>Example Blog</title>
</head>
    <body>
        <div class="container">
            <header class="header">
                <span id="burger"><i class="fas fa-bars"></i></span>
                <a class="logo" href="{% url 'index' %}"><span class="example">Example</span> Blog<br><span class="description">How work your favorite sites?</span></a>
                {% if user.is_authenticated %}
                <a href="/user/{{request.user.id}}" class="signup"><span class="link-center">{{ user.username }} </span><img src="{{ user.image.url }}" alt="User" class="img"></a>
                {% else %}
                <a href="{% url 'signup' %}" class="signup"><span class="link-center">Sign Up/Log in</span><img src="{% static 'icon.png' %}" alt="User" class="img"></a>
                {% endif %}
            </header>
            <a href="/admin/" class="interesting-button"><img src="{% static 'button2.png' %}" alt="interesting-button" id="interesting-button-img"></a>
            {% block content %}
    
            {% endblock %}
        </div>
        <script>
            (function(){
                let btn = document.getElementById('interesting-button-img');
                let burger = document.getElementById('burger');
                let find = false;
                let navbarClasses = document.getElementsByClassName('navbar')[0].classList;
                btn.addEventListener('mouseenter', function(){
                    setTimeout(() => {btn.setAttribute('src',"{% static 'button3.png' %}");}, 100);
                });
                btn.addEventListener('mouseleave', function(){
                    setTimeout(() => {btn.setAttribute('src',"{% static 'button2.png' %}");}, 100);
                });
                burger.addEventListener('click', function(){
                    if (navbarClasses[1]){
                        navbarClasses.remove('active');
                    }
                    else{
                        navbarClasses.add('active');
                    }
                })
            })();
        </script>
    </body>
</html>

schoolproject/templates/index.html
{% extends "base.html" %}
    {% block content %}
        {% load static %}
        
        <nav class="navbar">
            {% if request.user.is_authenticated %}
            <a href="{% url 'index' %}" class="nav-item"><i class="fas fa-newspaper"></i> Newsfeed</a><br>
            <a href="/user/{{request.user.id}}" class="nav-item"><i class="fas fa-user"></i> Profile</a><br>   
            <a href="" class="nav-item"><i class="fas fa-heart"></i> Favorites</a><br>
            <a href="{% url 'newpost' %}" class="nav-item"><i class="fas fa-plus"></i> New post</a><br>
            <a href="{% url 'logout' %}" class="nav-item"><i class="fas fa-sign-out-alt"></i> LogOut</a><br>
            {% endif %}
        </nav>
        {% for post in posts %}
            <div class="post" id="{{ post.id }}">
                <img class="post-img" src='{{ post.img.url }}'>
                <div class="post-text">
                    <a class="post-title" href="/post/{{post.id}}">{{ post.title }}</a><br><hr>
                    <div class="post-text-height">{{ post.text }}</div>
                    <a href="/user/{{ post.author.id }}/" class="author">{{ post.author }}</a>
                    {% if user.is_authenticated %}
                      {% if post.is_liked_by_current_user %}
                          <div class="rate" style="color: #ED002F;">{{post.likes}} <a href="like/add/{{post.id}}/{{user.id}}/#{{post.id}}"><i class="fas fa-heart" style="font-size: 16pt;color: #ED002F;"></i></a></div>
                      {% else %}
                          <div class="rate">{{post.likes}} <a href="like/add/{{post.id}}/{{user.id}}/#{{post.id}}"><i class="fas fa-heart" style="font-size: 16pt;"></i></a></div>
                      {% endif %}
                    {% endif %}
                    <i class="date">{{ post.pub_date }}</i>
                </div><br>
            </div>
        {% endfor %}
    {% endblock %}    

schoolproject/templates/newpost.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<form method="post" action="{% url 'newpost' %}" id="newpost" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="signup-form">
      <legend>New post</legend>
      <p><input type="text" name="title" maxlength="100" required="" id="id_title"></p>
      <p><textarea name="text" cols="40" rows="10" required="" id="id_text"></textarea></p>
      <p><input type="file" name="img" accept="image/*" required="" id="id_img"></p>
      <p><button type="submit" form="newpost">Post</button></p><br>
    </fieldset>
</form>
{% endblock %}

schoolproject/templates/post.html
{% extends "base.html" %}
    {% block content %}
        {% load static %}
        <link rel="stylesheet" href="{% static 'poststyle.css' %}">
            <div class="post">
                <img src="{{ post.img.url }}" class="post-image">
                <span class="title">{{post.title}}</span>
                <div class="text">{{post.text}}</div>
                <a class="name" href="/user/{{ post.author.id }}">{{post.author}}</a>
                <i class="post-date">{{post.pub_date}}</i>
            </div>
    {% endblock %}

schoolproject/templates/profile.html
{% extends "base.html" %}
    {% block content %}
        {% load static %}
        <link rel="stylesheet" href="{% static 'poststyle.css' %}">
        <div class="flex">
            <nav class="navbar">
                <a href="{% url 'index' %}" class="nav-item"><i class="fas fa-newspaper"></i> Newsfeed</a><br>
                <a href="" class="nav-item"><i class="fas fa-user"></i> Profile</a><br>
                <a href="" class="nav-item"><i class="fas fa-heart"></i> Favorites</a><br>
            </nav>
            <img class="user-image" src='{{ user.image.url }}'>
            <div class="user">
                <div class="post-text">
                    <span class="post-title" href="/user/{{user.username}}">{{ user.username }}</span><br>
                    <div class="post-text-height">
                        <span>{{ user.desc }}</span><br><br>
                        <i class="info">
                            Name: {{user.first_name}}<br>
                            Surname: {{user.last_name}}<br>
                            E-mail: {{user.email}}
                        </i>
                    </div>
                </div><br>
            </div>
        </div>
        {% for post in posts %}
            <div class="user-post">
                <img class="post-img" src='{{ post.img.url }}'>
                <div class="post-text">
                    <a class="post-title" href="/post/{{post.id}}">{{ post.title }}</a><br><hr>
                    <div class="post-text-height">{{ post.text }}</div>
                    {% if user.is_authenticated %}
                      {% if post.is_liked_by_current_user %}
                          <div class="rate" style="color: #ED002F;">{{post.likes}} <a href="../../like/add/{{post.id}}/{{user.id}}/#{{post.id}}"><i class="fas fa-heart" style="font-size: 16pt;color: #ED002F;"></i></a></div>
                      {% else %}
                          <div class="rate">{{post.likes}} <a href="../../like/add/{{post.id}}/{{user.id}}/#{{post.id}}"><i class="fas fa-heart" style="font-size: 16pt;"></i></a></div>
                      {% endif %}
                    {% endif %}
                    <i class="date">{{ post.pub_date }}</i>
                </div><br>
            </div>
        {% endfor %}

    {% endblock %} 

schoolproject/templates/template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.15.4-web/css/all.min.css' %}">
    <script defer src="{% static 'fontawesome-free-5.15.4-web/js/all.js' %}"></script>
    <link rel="stylesheet" href="{% static 'normalize.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'logo.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Shippori+Antique&display=swap" rel="stylesheet">
    <title>Example Blog</title>
</head>
    <body>
        <div class="container">
            <header class="header">
                <span id="burger"><i class="fas fa-bars"></i></span>
                <a class="logo" href="{% url 'index' %}"><span class="example">Example</span> Blog<br><span class="description">How work your favorite sites?</span></a>
                <a href="#" class="signup"><span class="link-center">Sign Up/Log in</span><img src="{% static 'icon.png' %}" alt="User" class="img"></a>
            </header>
            <a href="/admin/" class="interesting-button"><img src="{% static 'button2.png' %}" alt="interesting-button" id="interesting-button-img"></a>
            <nav class="navbar">
                <a href="{% url 'index' %}" class="nav-item"><i class="fas fa-newspaper"></i> Newsfeed</a><br>
                {% if request.user.is_authenticated %}
                    <a href="/user/{{request.user.id}}" class="nav-item"><i class="fas fa-user"></i> Profile</a><br>
                {% endif %}    
                <a href="" class="nav-item"><i class="fas fa-heart"></i> Favorites</a><br>
                <a href="" class="nav-item"><i class="fas fa-cogs"></i> Settings</a><br>
            </nav>
            {% for post in posts %}
                <div class="post">
                    <img class="post-img" src='{{ post.img.url }}'>
                    <div class="post-text">
                        <a class="post-title" href="/post/{{post.id}}">{{ post.title }}</a><br><hr>
                        <div class="post-text-height">{{ post.text }}</div>
                        <a href="/user/{{ post.author.id }}/" class="author">{{ post.author }}</a><i class="date">{{ post.pub_date }}</i>
                    </div><br>
                </div>

schoolproject/user/templates/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}

<form method="post" action="{% url 'signup' %}" id="signup" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <fieldset class="signup-form">
    <legend>Signup</legend>
    <p><input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username" placeholder="Username"></p>
    <p><input type="text" name="first_name" maxlength="150" id="id_first_name" placeholder="First name"></p>
    <p><input type="text" name="last_name" maxlength="150" id="id_last_name" placeholder="Last name"></p>
    <p><textarea name="desc" cols="40" rows="10" maxlength="30" required="" id="id_desc" placeholder="Status"></textarea></p>
    <p><input type="email" name="email" maxlength="254" id="id_email" placeholder="Email"></p>
    <p><input type="file" name="image" accept="image/*" required="" id="id_image" placeholder="Photo"></p>
    <p><input type="password" name="password1" autocomplete="new-password" required="" id="id_password1" aria-autocomplete="list" placeholder="Password"></p>
    <p><input type="password" name="password2" autocomplete="new-password" required="" id="id_password2" placeholder="Confirm password"></p>
    <p><button type="submit" form="signup">Зарегистрироваться</button></p><br>
    <a href="{% url 'login' %}" class="isnt-registred">Уже зарегистрированы?</a>
  </fieldset><br>
</form>
{% endblock %}